/** Mirrors PostgreSQL enum: student_stage — 22 journey stages (PRD §6) */
export enum StudentStage {
  REGISTERED_STUDENT = 'registered_student',
  DOCUMENTS_PENDING = 'documents_pending',
  DOCUMENTS_COMPLETE = 'documents_complete',
  APPLICATION_SUBMITTED = 'application_submitted',
  UNDER_REVIEW = 'under_review',
  OFFER_RECEIVED = 'offer_received',
  OFFER_ACCEPTED = 'offer_accepted',
  FINANCIAL_REVIEW = 'financial_review',
  PROFILE_EVALUATION = 'profile_evaluation',
  UNIVERSITY_SELECTION = 'university_selection',
  COUNSELLING_COMPLETED = 'counselling_completed',
  CONTACTED_SCHEDULED = 'contacted_scheduled',
  VISA_DOCUMENTATION = 'visa_documentation',
  VISA_SUBMITTED = 'visa_submitted',
  BIOMETRICS_COMPLETED = 'biometrics_completed',
  VISA_APPROVED = 'visa_approved',
  PRE_DEPARTURE = 'pre_departure',
  TRAVEL_CONFIRMED = 'travel_confirmed',
  DEPARTED = 'departed',
  ARRIVED_SUCCESSFULLY = 'arrived_successfully',
  ACTIVE_STUDENT = 'active_student',
  CASE_CLOSED = 'case_closed',
}

export const STUDENT_STAGE_LABELS: Record<StudentStage, string> = {
  [StudentStage.REGISTERED_STUDENT]: 'Registered Student',
  [StudentStage.DOCUMENTS_PENDING]: 'Documents Pending',
  [StudentStage.DOCUMENTS_COMPLETE]: 'Documents Complete',
  [StudentStage.APPLICATION_SUBMITTED]: 'Application Submitted',
  [StudentStage.UNDER_REVIEW]: 'Under Review',
  [StudentStage.OFFER_RECEIVED]: 'Offer Received',
  [StudentStage.OFFER_ACCEPTED]: 'Offer Accepted',
  [StudentStage.FINANCIAL_REVIEW]: 'Financial Review',
  [StudentStage.PROFILE_EVALUATION]: 'Profile Evaluation',
  [StudentStage.UNIVERSITY_SELECTION]: 'University Selection',
  [StudentStage.COUNSELLING_COMPLETED]: 'Counselling Completed',
  [StudentStage.CONTACTED_SCHEDULED]: 'Contacted / Scheduled',
  [StudentStage.VISA_DOCUMENTATION]: 'Visa Documentation',
  [StudentStage.VISA_SUBMITTED]: 'Visa Submitted',
  [StudentStage.BIOMETRICS_COMPLETED]: 'Biometrics Completed',
  [StudentStage.VISA_APPROVED]: 'Visa Approved',
  [StudentStage.PRE_DEPARTURE]: 'Pre-Departure',
  [StudentStage.TRAVEL_CONFIRMED]: 'Travel Confirmed',
  [StudentStage.DEPARTED]: 'Departed',
  [StudentStage.ARRIVED_SUCCESSFULLY]: 'Arrived Successfully',
  [StudentStage.ACTIVE_STUDENT]: 'Active Student',
  [StudentStage.CASE_CLOSED]: 'Case Closed',
};

export const STUDENT_STAGE_ORDER: StudentStage[] = [
  StudentStage.REGISTERED_STUDENT,
  StudentStage.DOCUMENTS_PENDING,
  StudentStage.DOCUMENTS_COMPLETE,
  StudentStage.APPLICATION_SUBMITTED,
  StudentStage.UNDER_REVIEW,
  StudentStage.OFFER_RECEIVED,
  StudentStage.OFFER_ACCEPTED,
  StudentStage.FINANCIAL_REVIEW,
  StudentStage.PROFILE_EVALUATION,
  StudentStage.UNIVERSITY_SELECTION,
  StudentStage.COUNSELLING_COMPLETED,
  StudentStage.CONTACTED_SCHEDULED,
  StudentStage.VISA_DOCUMENTATION,
  StudentStage.VISA_SUBMITTED,
  StudentStage.BIOMETRICS_COMPLETED,
  StudentStage.VISA_APPROVED,
  StudentStage.PRE_DEPARTURE,
  StudentStage.TRAVEL_CONFIRMED,
  StudentStage.DEPARTED,
  StudentStage.ARRIVED_SUCCESSFULLY,
  StudentStage.ACTIVE_STUDENT,
  StudentStage.CASE_CLOSED,
];
