export const ErrorCodes = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // Leads
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  LEAD_ALREADY_CONVERTED: 'LEAD_ALREADY_CONVERTED',
  DUPLICATE_PHONE: 'DUPLICATE_PHONE',

  // Students
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',

  // Fees
  FEE_NOT_FOUND: 'FEE_NOT_FOUND',
  FEE_ALREADY_ASSIGNED: 'FEE_ALREADY_ASSIGNED',
  FEE_HAS_PAYMENTS: 'FEE_HAS_PAYMENTS',
  AMOUNT_BELOW_PAID: 'AMOUNT_BELOW_PAID',

  // Payments
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  EXCEEDS_REMAINING: 'EXCEEDS_REMAINING',
  CONFIRM_REQUIRED: 'CONFIRM_REQUIRED',

  // Storage
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  SIGNED_URL_FAILED: 'SIGNED_URL_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // Applications
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  DUPLICATE_APPLICATION: 'DUPLICATE_APPLICATION',

  // Tasks
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',

  // Follow-ups
  FOLLOWUP_NOT_FOUND: 'FOLLOWUP_NOT_FOUND',

  // Employees
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  CANNOT_DEACTIVATE_SELF: 'CANNOT_DEACTIVATE_SELF',
  USER_HAS_ACTIVE_ASSIGNMENTS: 'USER_HAS_ACTIVE_ASSIGNMENTS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
